# This is a config for E2B sandbox template.
# You can use template ID (7ku8nc31om4t6s1suxcd) or template name (cortex-nextjs-v3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("cortex-nextjs-v3") # Sync sandbox
# sandbox = await AsyncSandbox.create("cortex-nextjs-v3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('cortex-nextjs-v3')

team_id = "1c356444-74a8-4711-ae73-80ea663e72f3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "cortex-nextjs-v3"
template_id = "7ku8nc31om4t6s1suxcd"
